---
# Cleanup tasks for MSSQL InSpec role

- name: Generate summary report
  template:
    src: summary_report.j2
    dest: "{{ inspec_results_dir }}/summary_report_{{ ansible_date_time.epoch }}.txt"
  when: generate_summary_report | default(true)

- name: Clean up temporary directory
  file:
    path: "{{ inspec_temp_dir }}"
    state: absent
  when: cleanup_temp_files | default(true)

- name: Send results to Splunk if enabled
  include_tasks: splunk_integration.yml
  when:
    - send_to_splunk | default(false) | bool
    - splunk_hec_url is defined
    - splunk_hec_token is defined