---
# InSpec execution tasks for MSSQL

- name: Execute InSpec controls for each file
  shell: |
    /usr/bin/inspec exec {{ item.path }} \
      --input usernm={{ mssql_username }} \
              passwd={{ mssql_password }} \
              hostnm={{ mssql_server }} \
              servicenm={{ mssql_service | default('') }} \
              port={{ mssql_port }} \
      --reporter=json-min \
      --no-color
  register: inspec_results
  loop: "{{ control_files.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  changed_when: false
  failed_when: false
  no_log: "{{ not inspec_debug_mode | default(true) }}"

- name: Process InSpec results
  include_tasks: process_results.yml
  loop: "{{ inspec_results.results }}"
  loop_control:
    index_var: idx
    label: "Processing result {{ idx + 1 }}"