---
# Setup tasks for MSSQL InSpec role

- name: Setup InSpec environment on delegate host
  block:
    - name: Create results directory
      file:
        path: "{{ inspec_results_dir }}"
        state: directory
        mode: '0755'

    - name: Create temporary working directory
      file:
        path: "{{ inspec_temp_dir }}"
        state: directory
        mode: '0755'

    - name: Find all Ruby control files for specified MSSQL version
      find:
        paths: "{{ role_path }}/files/MSSQL{{ mssql_version }}_ruby"
        patterns: "*.rb"
      register: control_files

    - name: Display control files to be executed
      debug:
        msg: "Found {{ control_files.files | length }} control file(s) for MSSQL {{ mssql_version }}"
      when: inspec_debug_mode | default(false)
  delegate_to: "{{ inspec_delegate_host }}"
