---
# Validation tasks for MSSQL InSpec role

- name: Handle sensitive connection parameters
  block:
    - name: Set database connection parameters
      set_fact:
        mssql_connection:
          server: "{{ mssql_server }}"
          port: "{{ mssql_port }}"
          database: "{{ mssql_database }}"
          username: "{{ mssql_username }}"
          password: "{{ mssql_password }}"
          version: "{{ mssql_version }}"

    - name: Validate required parameters
      assert:
        that:
          - mssql_server is defined
          - mssql_port is defined
          - mssql_database is defined
          - mssql_username is defined
          - mssql_password is defined
          - mssql_version is defined
        fail_msg: "Required MSSQL connection parameters are missing"
  no_log: true

- name: Check if InSpec is installed
  command: which inspec
  register: inspec_check
  changed_when: false
  failed_when: false
  delegate_to: "{{ inspec_delegate_host }}"

- name: Fail if InSpec is not installed
  fail:
    msg: "InSpec is not installed. Please install InSpec before running this role."
  when: inspec_check.rc != 0

- name: Check if MSSQL version directory exists
  stat:
    path: "{{ role_path }}/files/MSSQL{{ mssql_version }}_ruby"
  register: version_dir_check
  delegate_to: "{{ inspec_delegate_host }}"

- name: Fail if MSSQL version directory doesn't exist
  fail:
    msg: "MSSQL version {{ mssql_version }} is not supported. Directory MSSQL{{ mssql_version }}_ruby not found."
  when: not version_dir_check.stat.exists