---
# Oracle result processing tasks

- name: Set Oracle result file names (matching original script pattern)
  set_fact:
    oracle_control_file_name: "{{ oracle_control_files.files[idx].path | basename | regex_replace('\\.rb$', '') }}"
    oracle_timestamp: "{{ ansible_date_time.epoch }}"
    oracle_process_id: "{{ ansible_process_id | default(ansible_date_time.epoch) }}"
    oracle_platform: "ORACLE"

- name: Set Oracle result file name
  set_fact:
    oracle_result_file_name: "{{ oracle_platform }}_NIST_{{ oracle_process_id }}_{{ oracle_server }}_{{ oracle_database }}_{{ oracle_version }}_{{ oracle_timestamp }}_{{ oracle_control_file_name }}"

- name: Parse Oracle InSpec result status (matching original script logic)
  set_fact:
    oracle_inspec_status: "{{ (item.stdout | regex_search('\"status\":\"([^\"]+)\"', '\\1')) | default('unknown') }}"
  ignore_errors: true

- name: Handle successful Oracle InSpec execution
  block:
    - name: Save successful Oracle results to JSON file
      copy:
        content: "{{ item.stdout }}"
        dest: "{{ inspec_results_dir }}/{{ oracle_result_file_name }}.json"
      delegate_to: "{{ inspec_delegate_host }}"
      when: oracle_inspec_status is defined and oracle_inspec_status in ['passed', 'failed', 'skipped']

    - name: Log successful Oracle execution
      debug:
        msg: "Oracle control {{ oracle_control_file_name }} completed with status: {{ oracle_inspec_status }}"
      when: inspec_debug_mode | default(false)

- name: Handle failed Oracle InSpec execution
  block:
    - name: Create Oracle error report matching original script format
      copy:
        content: |
          {"controls":[{"timestamp":"","hostname":"{{ oracle_server }}","database":"{{ oracle_database }}","port":"{{ oracle_port }}","DBVersion":"{{ oracle_version }}","id":"Cannot connect to Oracle database. One or more parameters such as Platform, Host Name, Database Name, Service Name, Port Number, Database Version may be incorrect.","profile_id":"N/A","profile_sha256":"N/A","status":"Unreachable","code_desc":"Cannot connect to Oracle","statistics":{"duration":0},"version":"N/A"}]}
        dest: "{{ inspec_results_dir }}/{{ oracle_result_file_name }}.json"
      delegate_to: "{{ inspec_delegate_host }}"
      when:
        - item.rc != 0 or (oracle_inspec_status is not defined or oracle_inspec_status not in ['passed', 'failed', 'skipped'])

    - name: Log Oracle connection error
      debug:
        msg: |
          Oracle control {{ oracle_control_file_name }} failed to execute.
          Error: {{ item.stderr | default('Unknown Oracle error') }}
          Result file: {{ oracle_result_file_name }}.json
      when:
        - inspec_debug_mode | default(false)
        - (item.rc != 0 or (oracle_inspec_status is not defined or oracle_inspec_status not in ['passed', 'failed', 'skipped']))
