# Development Environment Input Configuration
# Configure these values for your development environment

resource_group_name: "rg-aso-dev"
aks_cluster_name: "aks-dev-cluster"
key_vault_name: "kv-aso-dev-001"
uami_name: "uami-aso-workload-dev"
vnet_name: "vnet-aso-dev"
environment: "dev"

required_tags:
  - "environment"
  - "owner"
  - "project"

compliance_frameworks:
  - "CIS"
  - "Azure Security Benchmark"
  - "NIST"