# Staging Environment Input Configuration
# Configure these values for your staging environment

resource_group_name: "rg-aso-staging"
aks_cluster_name: "aks-staging-cluster"
key_vault_name: "kv-aso-staging-001"
uami_name: "uami-aso-workload-staging"
vnet_name: "vnet-aso-staging"
environment: "staging"

required_tags:
  - "environment"
  - "owner"
  - "cost-center"
  - "project"

compliance_frameworks:
  - "CIS"
  - "Azure Security Benchmark"
  - "NIST"