---
# Sybase parameter validation tasks

- name: Set Sybase database connection parameters
  set_fact:
    sybase_connection:
      server: "{{ sybase_server }}"
      port: "{{ sybase_port }}"
      database: "{{ sybase_database }}"
      service: "{{ sybase_service | default('') }}"
      username: "{{ sybase_username }}"
      password: "{{ sybase_password }}"
      version: "{{ sybase_version }}"
      ssh_enabled: "{{ sybase_use_ssh | default(true) }}"
      ssh_user: "{{ sybase_ssh_user | default('oracle') }}"

- name: Validate required Sybase parameters
  assert:
    that:
      - sybase_server is defined and sybase_server | length > 0
      - sybase_port is defined and sybase_port | int > 0
      - sybase_database is defined and sybase_database | length > 0
      - sybase_version is defined and sybase_version | length > 0
      - sybase_username is defined and sybase_username | length > 0
      - sybase_password is defined and sybase_password | length > 0
    fail_msg: "Missing required Sybase connection parameters"
    success_msg: "All Sybase parameters validated successfully"

- name: Validate SSH parameters (when SSH is enabled)
  assert:
    that:
      - sybase_ssh_user is defined and sybase_ssh_user | length > 0
      - sybase_ssh_password is defined and sybase_ssh_password | length > 0
    fail_msg: "Missing required SSH parameters for Sybase connection"
    success_msg: "SSH parameters validated successfully"
  when: sybase_use_ssh | default(true)

- name: Check if InSpec is installed
  command: which inspec
  register: inspec_check
  changed_when: false
  failed_when: false
  delegate_to: "{{ inspec_delegate_host }}"

- name: Fail if InSpec is not installed
  fail:
    msg: "InSpec is not installed. Please install InSpec before running Sybase compliance scans."
  when: inspec_check.rc != 0

- name: Check if Sybase version directory exists
  stat:
    path: "{{ sybase_controls_base_dir }}/SYBASE{{ sybase_version }}_ruby"
  register: sybase_version_dir
  delegate_to: "{{ inspec_delegate_host }}"

- name: Fail if Sybase version directory doesn't exist
  fail:
    msg: |
      Sybase version directory not found: {{ sybase_controls_base_dir }}/SYBASE{{ sybase_version }}_ruby
      Available versions: {{ sybase_controls_base_dir }}/SYBASE*_ruby
  when: not sybase_version_dir.stat.exists
